---
# tasks file for ansible-role-dell

- include_tasks: redhat.yml
  when:
    - ansible_connection != 'chroot'
    - ansible_system_vendor == "Dell Inc."
    - ansible_os_family == "RedHat"
    - install_dell_dsu
